### PR TITLE
get_popular_products() refactored to interact with DB

### PR DESCRIPTION
**Pull request by BlaiseRoberts**
## Associated Ticket
[Create Popular Products Table](https://github.com/solanum-tuberosums/bangazon_terminal_interface/issues/6)

## Description 
get_popular_products() refactored to interact with DB.  Right now, there is no way to complete orders, so you will not get anything back.  If you want to test on your machine you can comment out the sql line in the method that requires the o.date_paid (line 102) and you should get valid data returned and formatted to the table in the interface.

## All Tests Pass
- [x] Yes
- [ ] No

### CODE REVIEW

**Review by jessica-younker — COMMENTED** [review]
Need to round total for individual product revenues to 2 decimals.

**Review by jessica-younker — DISMISSED** [review]

**Review by JeremyBakker — DISMISSED** [review]
This looks good and functions as expected. Thanks!

**Review by JeremyBakker — APPROVED** [review]
Thanks

**Review by willsims14 — APPROVED** [review]
It works 💯

**Pull request merged**
