### PR TITLE
wrote create table SQL statements

### PR DESCRIPTION
**Pull request by willsims14**
## Associated Ticket
Applicable to all

## Description 
Database should be created when these statements are run.

## All Tests Pass
- [x] No

### CODE REVIEW

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
Can you reorder the DROP statements to account for the foreign key constraints? CustomerOrder and PaymentType should be above Customer.

**Review by zakspence — DISMISSED** [review]
Dope formatting

**Review by JeremyBakker — APPROVED** [review]
This looks great and works as expected. Thanks!

**Review by zakspence — APPROVED** [review]
aw chyea

**Pull request merged**
