### PR TITLE
Passing tests for flushing tables, saving customer, completing order, and saving to db

### PR DESCRIPTION
**Pull request by jessica-younker**
## Associated Ticket
none

## Description 
Texts for flushing tables, saving customer, completing order, and saving to db all pass. Current test_add_product_to_order method only passes with one product. When save_to_db method becomes dynamic, testing will pass with second product (currently line 95 in TestDB.py is commented out to allow test to pass--will update with refactoring).

## All Tests Pass
- [X] Yes

### CODE REVIEW

**Review by JeremyBakker — APPROVED** [review]
Looks good. Thanks!

**Review by willsims14 — APPROVED** [review]
💯

**Review by JeremyBakker — APPROVED** [review]

**Review by BlaiseRoberts — APPROVED** [review]
🥇

**Review by stevebrownlee — APPROVED** [review]
Wonderfully simple, hacked return values. Ship it.

**Pull request merged**
