### PR TITLE
TestDB.py file is fleshed out

### PR DESCRIPTION
**Pull request by BlaiseRoberts**
## Associated Ticket
All Feature Tickets.

## Description 
We have written tests for the different features of our project.  These features use 5 different methods:
```
save_to_db
get_all_from_table
flush_table
get_active_customer_order
complete_order
```

## All Tests Pass
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by willsims14 — DISMISSED** [review]
Now it properly fails.

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
We need to remove the TestUser.py file

**Review by jessica-younker — DISMISSED** [review]
Fail

**Review by JeremyBakker — APPROVED** [review]
6 tests fail.

**Review by zakspence — APPROVED** [review]
I approve these failing tests

**Pull request merged**
