### PR TITLE
removed global variables from main.py

### PR DESCRIPTION
**Pull request by jessica-younker**
## Associated Ticket
none

## Description 
Now that the recursive behavior run_ordering_system in main.py has been removed, we no longer need global variables.

## All Tests Pass
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by JeremyBakker — CHANGES_REQUESTED** [review]
I found a little bug. When trying to complete an order without a payment type, the interface prompts me to create a payment type. When I select "Y," the interface shoots me back to the main screen. Can you check that out?

**Review by JeremyBakker — DISMISSED** [review]
I will move my comment to a bug ticket.

**Review by willsims14 — APPROVED** [review]
Looks good, thanks

**Review by zakspence — APPROVED** [review]
looks good

**Pull request merged**
