### PR TITLE
added docstrings for complete methods in methods.py

### PR DESCRIPTION
**Pull request by JeremyBakker**
## Associated Ticket
ALL

## Description 
I have added docstrings for the existing methods in methods.py. I also made sure all code fits within a 79-space ruler and standardized variable names, changing "command" to "sql" as the defining variable for SQL statements. 

## All Tests Pass
- [x] Yes
- [ ] No

### CODE REVIEW

**Review by BlaiseRoberts — COMMENTED** [review]
🥇

**Review by BlaiseRoberts — DISMISSED** [review]
💯

**Review by willsims14 — DISMISSED** [review]
Looks good 💯

**Review by jessica-younker — DISMISSED** [review]

**Review by willsims14 — DISMISSED** [review]
Still looks great after after conflicts were resolved.

**Review by willsims14 — APPROVED** [review]
💯

**Review by jessica-younker — APPROVED** [review]

**Pull request merged**
